-- Migration: 202606240003_fix_request_document_code_prefixes.sql
-- Rewrites generic SOL prefixes assigned during backfill when request_types.code is autogenerated.

WITH typed_requests AS (
  SELECT
    er.id,
    er.request_sequence,
    UPPER(
      REGEXP_REPLACE(
        TRANSLATE(
          COALESCE(NULLIF(rt.name, ''), rt.code, ''),
          U&'\00C1\00C9\00CD\00D3\00DA\00DC\00D1\00E1\00E9\00ED\00F3\00FA\00FC\00F1',
          'AEIOUUNaeiouun'
        ),
        '[^A-Za-z0-9]+',
        '_',
        'g'
      )
    ) AS type_token
  FROM public.employee_requests er
  LEFT JOIN public.request_types rt ON rt.id = er.request_type_id
  WHERE er.request_sequence IS NOT NULL
    AND er.request_code LIKE 'F-RRHH-SOL-SOL-%'
),
resolved_prefixes AS (
  SELECT
    id,
    request_sequence,
    CASE
      WHEN type_token IN ('VACATION', 'VAC', 'VACACIONES', 'DESCANSO_VACACIONAL') THEN 'VAC'
      WHEN type_token IN ('MEDICAL_LEAVE', 'MEDICAL', 'DESCANSO_MEDICO', 'DESCANSO', 'DM') THEN 'DME'
      WHEN type_token IN ('UNPAID_LEAVE', 'PERSONAL_PERMISSION', 'PERMISO_PERSONAL', 'PERMISO', 'LEAVE_PERMISSION') THEN 'PER'
      WHEN type_token IN ('ABSENCE_JUSTIFICATION', 'JUSTIFICACION_INASISTENCIA', 'JUSTIFICACION_DE_INASISTENCIA', 'INASISTENCIA', 'ABSENCE') THEN 'JIN'
      WHEN type_token IN ('SHIFT_CHANGE', 'SCHEDULE_CHANGE', 'CAMBIO_HORARIO', 'CAMBIO_DE_HORARIO', 'CAMBIO_TURNO', 'CAMBIO_DE_TURNO') THEN 'CHO'
      WHEN type_token IN ('FAMILY_SERIOUS_ILLNESS_LEAVE', 'FAMILY_LEAVE', 'LICENCIA_FAMILIAR_GRAVE', 'LICENCIA_POR_FAMILIAR_GRAVE', 'FAMILIAR_GRAVE') THEN 'LFG'
      ELSE 'SOL'
    END AS prefix
  FROM typed_requests
)
UPDATE public.employee_requests er
SET request_code = 'F-RRHH-SOL-' || resolved_prefixes.prefix || '-' || LPAD(resolved_prefixes.request_sequence::TEXT, 6, '0'),
    updated_at = NOW()
FROM resolved_prefixes
WHERE er.id = resolved_prefixes.id
  AND resolved_prefixes.prefix <> 'SOL';
