-- Some company request types were created with autogenerated codes such as
-- REQ_aad6e9 while their names still contain the canonical business type.
-- Attendance and payroll integrations should see canonical codes consistently.

WITH typed_request_types AS (
  SELECT
    id,
    UPPER(
      REGEXP_REPLACE(
        TRANSLATE(COALESCE(code, ''), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN'),
        '[-\s]+',
        '_',
        'g'
      )
    ) AS code_token,
    UPPER(
      REGEXP_REPLACE(
        TRANSLATE(COALESCE(name, ''), 'áéíóúÁÉÍÓÚñÑ', 'aeiouAEIOUnN'),
        '[-\s]+',
        '_',
        'g'
      )
    ) AS name_token
  FROM public.request_types
),
canonical_types AS (
  SELECT
    id,
    CASE
      WHEN code_token IN ('VAC', 'VACATION', 'VACACIONES', 'DESCANSO_VACACIONAL', 'VACACIONAL')
        OR name_token IN ('VAC', 'VACATION', 'VACACIONES', 'DESCANSO_VACACIONAL', 'VACACIONAL')
        THEN 'VACATION'
      WHEN code_token IN ('MEDICAL', 'MEDICAL_LEAVE', 'DESCANSO_MEDICO', 'DESCANSO', 'DM', 'CERTIFICADO_MEDICO', 'LICENCIA_MEDICA')
        OR name_token IN ('MEDICAL', 'MEDICAL_LEAVE', 'DESCANSO_MEDICO', 'DESCANSO', 'DM', 'CERTIFICADO_MEDICO', 'LICENCIA_MEDICA')
        THEN 'MEDICAL_LEAVE'
      WHEN code_token IN ('UNPAID_LEAVE', 'PERSONAL_PERMISSION', 'PERMISO_PERSONAL', 'LEAVE_PERMISSION', 'PERMISO', 'PERM')
        OR name_token IN ('UNPAID_LEAVE', 'PERSONAL_PERMISSION', 'PERMISO_PERSONAL', 'LEAVE_PERMISSION', 'PERMISO', 'PERM')
        THEN 'UNPAID_LEAVE'
      ELSE NULL
    END AS canonical_code
  FROM typed_request_types
)
UPDATE public.request_types rt
SET code = canonical_types.canonical_code,
    affects_attendance = TRUE,
    affects_payroll = TRUE,
    updated_at = NOW()
FROM canonical_types
WHERE rt.id = canonical_types.id
  AND canonical_types.canonical_code IS NOT NULL
  AND (
    rt.code IS DISTINCT FROM canonical_types.canonical_code
    OR COALESCE(rt.affects_attendance, FALSE) IS DISTINCT FROM TRUE
    OR COALESCE(rt.affects_payroll, FALSE) IS DISTINCT FROM TRUE
  );
